from __future__ import annotations
import streamlit as st
from repositories.artifact_repository import artifact_repository
from ui.artifacts.artifact_cards_v2 import render_artifact_cards_v2
from ui.artifacts.artifact_viewer_framework import render_artifact_viewer

def render_artifact_explorer(extraction_id: str, project_id: str = "default"):
    artifacts = artifact_repository.list_by_extraction(extraction_id)
    st.subheader("Generated Knowledge")
    st.caption(f"{len(artifacts)} artifact(s) generated by this extraction.")
    if not artifacts:
        st.info("No artifacts found for this extraction.")
        return
    render_artifact_cards_v2(artifacts)
    selected_id = st.session_state.get("selected_artifact_id")
    selected = next((a for a in artifacts if a["id"] == selected_id), None)
    if selected:
        st.divider()
        render_artifact_viewer(selected)
